### PR TITLE
Adds OBS Ninja

### PR DESCRIPTION
**Pull request by xliiv**

### CODE REVIEW

**Comment by croqaz** [comment]
Thank you @xliiv for adding the link! I didn't know about it and I thinks is great!!
However do you mind if you add the Github repo instead of the .ninja URL?
Because it seems to me that there's many other useful URLs that can be found in the README from the repo, and it's better to use that as an entry point into the project.
Thanks :)

**Comment by xliiv** [comment]
Done.

I'm glad you like.

Cool repo :+1:

**Comment by croqaz** [comment]
Thank you very much :)

**Comment by xliiv** [comment]
Thank you for the repo :)

**Pull request merged**
